import { Order } from "@/types/orders";

export const columns = [
  { name: "ORDER", uid: "order_id" },
  { name: "STAGE", uid: "fulfillment_stage" },
  { name: "PROGRESS", uid: "stage_progress_percentage" },
  { name: "AMOUNT", uid: "amount" },
  { name: "ORDER STATUS", uid: "order_status" },
  { name: "PAYMENT STATUS", uid: "payment_status" },
  { name: "ETA", uid: "expected_completion_date" },
];

export const orders: Order[] = [
  {
    order_id: "SUN-20451",
    order_status: "BALANCE_DUE",
    order_status_label: "Balance Due",
    payment_status: "REMAINING_BALANCE_DUE",
    payment_status_label: "Remaining Balance Due",
    customer_name: "Sienna Patel",
    payment_summary: {
      total_amount: 98400,
      amount_paid: 29520,
      balance_remaining: 68880,
      currency: "USD",
      status: "REMAINING_BALANCE_DUE",
      status_label: "Remaining Balance Due",
      pay_now_available: true,
      pay_now_url: "/orders/SUN-20451/invoice",
      pay_now_action: {
        cta: "Pay Now",
        redirect_to: "/orders/SUN-20451/invoice",
      },
    },
    go_live_tracking: [
      { stage: "Purchase", status: "COMPLETED", started_at: "2024-11-18T10:15:00Z", completed_at: "2024-11-18T10:20:00Z" },
      { stage: "Fulfillment", status: "IN_PROGRESS", started_at: "2024-11-19T08:00:00Z", notes: "Rack slot confirming" },
      { stage: "Energy Infrastructure Installation", status: "PENDING" },
      { stage: "Provisioning", status: "PENDING" },
      { stage: "Testing", status: "PENDING" },
      { stage: "Activation", status: "PENDING" },
    ],
    documents: {
      invoice_available: true,
      receipt_available: false,
      management_agreement_pdf: "/docs/SUN-20451-agreement.pdf",
    },
    fulfillment_stage: "Rack Assignment",
    stage_progress_percentage: 82,
    provisioning_complete: false,
    expected_completion_date: "2024-12-08T00:00:00Z",
    status: "ACTIVE",
    createdAt: "2024-11-18T10:15:00Z",
    updatedAt: "2024-11-28T09:00:00Z",
    stages_timeline: [
      {
        stage: "Payment Verified",
        status: "COMPLETED",
        started_at: "2024-11-18T10:15:00Z",
        completed_at: "2024-11-18T10:20:00Z",
        notes: "Stripe ACH - cleared",
      },
      {
        stage: "KYC & Compliance",
        status: "COMPLETED",
        started_at: "2024-11-18T10:20:00Z",
        completed_at: "2024-11-18T10:50:00Z",
        notes: "ID matched to billing profile",
      },
      {
        stage: "Rack Assignment",
        status: "IN_PROGRESS",
        started_at: "2024-11-19T08:00:00Z",
        notes: "Waiting on PDU slot confirmation",
      },
      {
        stage: "Provisioning",
        status: "PENDING",
        started_at: "2024-11-30T09:00:00Z",
        notes: "Auto-start once rack lock is confirmed",
      },
    ],
    order_details: {
      total_amount: 98400,
      currency: "USD",
      asic_models: [
        { model: "Antminer S21 Pro", quantity: 10, unit_price: 6800 },
        { model: "WhatsMiner M60", quantity: 4, unit_price: 7200 },
      ],
      products: [
        {
          productType: "Antminer S21 Pro",
          quantity: 10,
          unitPrice: 6800,
          totalPrice: 68000,
          isBooster: false,
          asicSpec: {
            model: "S21 Pro",
            hashRate: "234 TH/s",
            power: "3550 W",
            efficiency: "15.2 J/TH",
          },
        },
        {
          productType: "WhatsMiner M60",
          quantity: 4,
          unitPrice: 7200,
          totalPrice: 28800,
          isBooster: false,
          asicSpec: {
            model: "M60",
            hashRate: "186 TH/s",
            power: "3410 W",
            efficiency: "18.3 J/TH",
          },
        },
      ],
      boosters: [
        {
          productType: "Boosted Cooling Rail",
          quantity: 4,
          unitPrice: 400,
          totalPrice: 1600,
          isBooster: true,
        },
      ],
    },
    notifications_sent: [
      { type: "rack_assignment_pending", sent_at: "2024-11-25T12:00:00Z", channel: "email" },
      { type: "compliance_verified", sent_at: "2024-11-18T10:50:00Z", channel: "email" },
    ],
  },
  {
    order_id: "SUN-20488",
    order_status: "IN_PROGRESS",
    order_status_label: "In Progress",
    payment_status: "REMAINING_BALANCE_DUE",
    payment_status_label: "Remaining Balance Due",
    customer_name: "Diego Ramos",
    payment_summary: {
      total_amount: 91920,
      amount_paid: 61300,
      balance_remaining: 30620,
      currency: "USD",
      status: "REMAINING_BALANCE_DUE",
      status_label: "Remaining Balance Due",
      pay_now_available: true,
      pay_now_url: "/orders/SUN-20488/invoice",
      pay_now_action: {
        cta: "Pay Now",
        redirect_to: "/orders/SUN-20488/invoice",
      },
    },
    go_live_tracking: [
      { stage: "Purchase", status: "COMPLETED", started_at: "2024-11-22T12:00:00Z", completed_at: "2024-11-22T12:05:00Z" },
      { stage: "Fulfillment", status: "COMPLETED", started_at: "2024-11-23T09:00:00Z", completed_at: "2024-11-23T13:30:00Z" },
      { stage: "Energy Infrastructure Installation", status: "IN_PROGRESS", started_at: "2024-11-24T08:00:00Z", notes: "Rack power balancing" },
      { stage: "Provisioning", status: "IN_PROGRESS", started_at: "2024-11-24T08:00:00Z", notes: "Hashboards 5/12 synced" },
      { stage: "Testing", status: "PENDING" },
      { stage: "Activation", status: "PENDING" },
    ],
    documents: {
      invoice_available: true,
      receipt_available: false,
      management_agreement_pdf: "/docs/SUN-20488-agreement.pdf",
    },
    fulfillment_stage: "Provisioning",
    stage_progress_percentage: 47,
    provisioning_complete: false,
    expected_completion_date: "2024-12-12T00:00:00Z",
    status: "ACTIVE",
    createdAt: "2024-11-22T12:00:00Z",
    updatedAt: "2024-11-28T08:30:00Z",
    stages_timeline: [
      {
        stage: "Payment Verified",
        status: "COMPLETED",
        started_at: "2024-11-22T12:00:00Z",
        completed_at: "2024-11-22T12:05:00Z",
        notes: "Card - Visa",
      },
      {
        stage: "KYC & Compliance",
        status: "COMPLETED",
        started_at: "2024-11-22T12:05:00Z",
        completed_at: "2024-11-22T12:40:00Z",
      },
      {
        stage: "Rack Assignment",
        status: "COMPLETED",
        started_at: "2024-11-23T09:00:00Z",
        completed_at: "2024-11-23T13:30:00Z",
        notes: "Rack 14B - Dual PDU",
      },
      {
        stage: "Provisioning",
        status: "IN_PROGRESS",
        started_at: "2024-11-24T08:00:00Z",
        notes: "Hashboards 5/12 synced",
      },
    ],
    order_details: {
      total_amount: 91920,
      currency: "USD",
      asic_models: [{ model: "Antminer S19k Pro", quantity: 12, unit_price: 7600 }],
      products: [
        {
          productType: "Antminer S19k Pro",
          quantity: 12,
          unitPrice: 7600,
          totalPrice: 91200,
          isBooster: false,
          asicSpec: {
            model: "S19k Pro",
            hashRate: "120 TH/s",
            power: "2760 W",
            efficiency: "23 J/TH",
          },
        },
      ],
      boosters: [
        {
          productType: "Firmware Boost Pack",
          quantity: 12,
          unitPrice: 60,
          totalPrice: 720,
          isBooster: true,
        },
      ],
    },
    notifications_sent: [
      { type: "provisioning_started", sent_at: "2024-11-24T08:00:00Z", channel: "sms" },
      { type: "rack_assignment_complete", sent_at: "2024-11-23T13:30:00Z", channel: "email" },
    ],
  },
  {
    order_id: "SUN-20510",
    order_status: "ACTIVATED",
    order_status_label: "Activated",
    payment_status: "PAID_IN_FULL",
    payment_status_label: "Paid in Full",
    customer_name: "Avery Chen",
    payment_summary: {
      total_amount: 49500,
      amount_paid: 49500,
      balance_remaining: 0,
      currency: "USD",
      status: "PAID_IN_FULL",
      status_label: "Paid in Full",
      pay_now_available: false,
      pay_now_url: "/orders/SUN-20510/invoice",
      pay_now_action: null,
    },
    go_live_tracking: [
      { stage: "Purchase", status: "COMPLETED", started_at: "2024-11-26T09:15:00Z", completed_at: "2024-11-26T09:17:00Z" },
      { stage: "Fulfillment", status: "COMPLETED", started_at: "2024-11-26T10:00:00Z", completed_at: "2024-11-26T14:20:00Z" },
      { stage: "Energy Infrastructure Installation", status: "COMPLETED", started_at: "2024-11-27T09:00:00Z", completed_at: "2024-11-27T18:00:00Z" },
      { stage: "Provisioning", status: "COMPLETED", started_at: "2024-11-27T09:00:00Z", completed_at: "2024-11-27T18:00:00Z" },
      { stage: "Testing", status: "IN_PROGRESS", started_at: "2024-11-28T08:00:00Z", notes: "Board 2 hash rate instability flagged" },
      { stage: "Activation", status: "PENDING" },
    ],
    documents: {
      invoice_available: true,
      receipt_available: true,
      management_agreement_pdf: "/docs/SUN-20510-agreement.pdf",
    },
    fulfillment_stage: "QA Burn-in",
    stage_progress_percentage: 15,
    provisioning_complete: false,
    expected_completion_date: "2024-12-18T00:00:00Z",
    status: "ON_HOLD",
    createdAt: "2024-11-26T09:15:00Z",
    updatedAt: "2024-11-28T12:10:00Z",
    stages_timeline: [
      {
        stage: "Payment Verified",
        status: "COMPLETED",
        started_at: "2024-11-26T09:15:00Z",
        completed_at: "2024-11-26T09:17:00Z",
      },
      {
        stage: "KYC & Compliance",
        status: "COMPLETED",
        started_at: "2024-11-26T09:17:00Z",
        completed_at: "2024-11-26T09:25:00Z",
      },
      {
        stage: "Rack Assignment",
        status: "COMPLETED",
        started_at: "2024-11-26T10:00:00Z",
        completed_at: "2024-11-26T14:20:00Z",
        notes: "Rack 3A - PDU A/B",
      },
      {
        stage: "Provisioning",
        status: "COMPLETED",
        started_at: "2024-11-27T09:00:00Z",
        completed_at: "2024-11-27T18:00:00Z",
        notes: "Firmware tuned to 140 TH/s",
      },
      {
        stage: "QA Burn-in",
        status: "IN_PROGRESS",
        started_at: "2024-11-28T08:00:00Z",
        notes: "Board 2 hash rate instability flagged",
      },
    ],
    order_details: {
      total_amount: 49500,
      currency: "USD",
      asic_models: [{ model: "WhatsMiner M50", quantity: 6, unit_price: 8100 }],
      products: [
        {
          productType: "WhatsMiner M50",
          quantity: 6,
          unitPrice: 8100,
          totalPrice: 48600,
          isBooster: false,
          asicSpec: {
            model: "M50",
            hashRate: "118 TH/s",
            power: "3300 W",
            efficiency: "28 J/TH",
          },
        },
      ],
      boosters: [
        {
          productType: "Remote Ops Pack",
          quantity: 1,
          unitPrice: 900,
          totalPrice: 900,
          isBooster: true,
        },
      ],
    },
    notifications_sent: [
      { type: "qa_burn_in_started", sent_at: "2024-11-28T08:00:00Z", channel: "slack" },
      { type: "provisioning_complete", sent_at: "2024-11-27T18:00:00Z", channel: "email" },
    ],
  },
];
